name:                templation
version:             0.1.0.0
github:              "grmble/stack-templates"
license:             MIT
license-file:        LICENSE
author:              "Juergen Gmeiner"
maintainer:          "spamless.juergen@gmail.com"
copyright:           "(c) 2019,2020 Juergen Gmeiner"


description:         Create and modify stack templates

# base 4.12 is ghc 8.6.x aka lts-14
dependencies:
- base >= 4.12 && < 5
- text
- bytestring
- directory
- attoparsec
- time
- unordered-containers
- data-default
- ansi-terminal
- unix-compat
- filepath
- string-conversions

library:
  source-dirs: src

tests:
  templation-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - templation
    - doctest
    - tasty
    - tasty-hunit
    - tasty-hedgehog
    - hedgehog

executables:
  templation:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - templation


ghc-options: -O2 -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
